# -*- coding: utf-8 -*-
"""Práctica 3 IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htL1xSaD182LpA1Xo4_dpjGb9YcxvxCA

# **Generative AI: GANs, LLMs y Agentic AI**

## **Carga del dataset y entrenamiento GAN**
"""

# ENTRENAMIENTO DE GAN PARA IMÁGENES DE MRI CEREBRAL
# Proyecto: Detección de Tumores Cerebrales


# Montar Google Drive para guardar el modelo
from google.colab import drive
drive.mount('/content/drive')

# Crear carpeta del proyecto en Drive
import os

PROJECT_PATH = '/content/drive/MyDrive/Practica_3_IA'
MODELS_PATH = os.path.join(PROJECT_PATH, 'modelos')
IMAGES_PATH = os.path.join(PROJECT_PATH, 'imagenes_generadas')
LOGS_PATH = os.path.join(PROJECT_PATH, 'logs')

for path in [PROJECT_PATH, MODELS_PATH, IMAGES_PATH, LOGS_PATH]:
    os.makedirs(path, exist_ok=True)

print(f"Carpeta del proyecto creada en: {PROJECT_PATH}")
print("Estructura:")
print(f"   ├── modelos/")
print(f"   ├── imagenes_generadas/")
print(f"   └── logs/")

# Instalación de Dependencias
!pip install kaggle --quiet
!pip install tensorflow==2.19.0 --quiet
!pip install matplotlib numpy pillow tqdm --quiet

print("Dependencias instaladas correctamente")

# Configuración de Kaggle para acceder al dataset

import os
KAGGLE_USERNAME = "hanfer05"
KAGGLE_KEY = "KGAT_065a546aa6a9946a11d4fa1147229d74"

# Crear directorio de Kaggle
os.makedirs('/root/.kaggle', exist_ok=True)

# Crear archivo kaggle.json con las credenciales
kaggle_json = f'''{{
    "username": "{KAGGLE_USERNAME}",
    "key": "{KAGGLE_KEY}"
}}'''

# Guardar el archivo
with open('/root/.kaggle/kaggle.json', 'w') as f:
    f.write(kaggle_json)

os.chmod('/root/.kaggle/kaggle.json', 0o600)

# Descargar y Extraer Dataset

# Descargar el dataset
!kaggle datasets download -d ishans24/brain-tumor-dataset -p /content/dataset

# extraer
import zipfile

with zipfile.ZipFile('/content/dataset/brain-tumor-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("Dataset descargado y extraído")

# estructura del dataset
!find /content/dataset -type d | head -20

# Exploración del Dataset
import os
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from glob import glob

# Encontrar todas las imágenes
DATASET_PATH = '/content/dataset'

# Buscar imágenes en todas las subcarpetas
all_images = []
for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']:
    all_images.extend(glob(os.path.join(DATASET_PATH, '**', ext), recursive=True))

print(f"Total de imágenes encontradas: {len(all_images)}")

# Mostrar estructura por carpetas
from collections import Counter
folders = [os.path.dirname(img).split('/')[-1] for img in all_images]
folder_counts = Counter(folders)
print("\nDistribución por carpeta:")
for folder, count in folder_counts.items():
    print(f"   - {folder}: {count} imágenes")

# Mostrar algunas imágenes de muestra
fig, axes = plt.subplots(2, 5, figsize=(15, 6))
sample_images = np.random.choice(all_images, 10, replace=False)

for ax, img_path in zip(axes.flatten(), sample_images):
    img = Image.open(img_path)
    ax.imshow(img, cmap='gray' if img.mode == 'L' else None)
    ax.set_title(os.path.dirname(img_path).split('/')[-1][:15])
    ax.axis('off')

plt.suptitle('Muestras del Dataset de MRI Cerebral', fontsize=14)
plt.tight_layout()
plt.savefig(os.path.join(IMAGES_PATH, 'muestras_dataset.png'), dpi=150)
plt.show()

print(f"\nImagen guardada en: {IMAGES_PATH}/muestras_dataset.png")

# Preprocesamiento de Datos

import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
from tqdm import tqdm

# Configuración
IMG_SIZE = 64  # Tamaño para la GAN (64x64)
BATCH_SIZE = 32
LATENT_DIM = 100

# Prepocesamos las imagenes para la GAN
# Redimensionamos a target_size
# Convertimos a RGB (3 canales)
# Normalizamos a rango [-1, 1]

def preprocess_images(image_paths, target_size=(IMG_SIZE, IMG_SIZE)):

    images = []
    failed = 0

    for path in tqdm(image_paths, desc="Procesando imágenes"):
        try:
            # Cargar imagen
            img = load_img(path, target_size=target_size)
            img_array = img_to_array(img)

            # Si es escala de grises, convertir a RGB
            if img_array.shape[-1] == 1:
                img_array = np.concatenate([img_array] * 3, axis=-1)

            # Normalizar a [-1, 1]
            img_array = (img_array - 127.5) / 127.5
            images.append(img_array)

        except Exception as e:
            failed += 1
            continue

    print(f"\nImágenes procesadas: {len(images)}")
    print(f"Imágenes fallidas: {failed}")

    return np.array(images)

# Procesar todas las imágenes
X_train = preprocess_images(all_images)

print(f"\nShape del dataset: {X_train.shape}")
print(f"Rango de valores: [{X_train.min():.2f}, {X_train.max():.2f}]")

# Crear dataset de TensorFlow
train_dataset = tf.data.Dataset.from_tensor_slices(X_train)
train_dataset = train_dataset.shuffle(buffer_size=1000).batch(BATCH_SIZE)

print(f"Dataset de TensorFlow creado con {len(train_dataset)} batches")

# Definición de la Arquitectura DCGAN

from tensorflow.keras import layers, Model
import tensorflow as tf

class DCGAN:

    def __init__(self, latent_dim=100, img_shape=(64, 64, 3)):
        self.latent_dim = latent_dim
        self.img_shape = img_shape

        # Construir modelos
        self.generator = self.build_generator()
        self.discriminator = self.build_discriminator()

        # Optimizadores
        self.gen_optimizer = tf.keras.optimizers.Adam(learning_rate=0.0002, beta_1=0.5)
        self.disc_optimizer = tf.keras.optimizers.Adam(learning_rate=0.0002, beta_1=0.5)

        # Loss
        self.cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

    def build_generator(self):
        # Generador: Transforma ruido aleatorio en imágenes de MRI.

        model = tf.keras.Sequential(name='Generator')

        # Capa inicial: Dense para crear feature maps
        model.add(layers.Dense(4 * 4 * 512, use_bias=False, input_shape=(self.latent_dim,)))
        model.add(layers.BatchNormalization())
        model.add(layers.LeakyReLU(0.2))
        model.add(layers.Reshape((4, 4, 512)))

        # Bloque 1: 4x4 -> 8x8
        model.add(layers.Conv2DTranspose(256, (5, 5), strides=(2, 2), padding='same', use_bias=False))
        model.add(layers.BatchNormalization())
        model.add(layers.LeakyReLU(0.2))

        # Bloque 2: 8x8 -> 16x16
        model.add(layers.Conv2DTranspose(128, (5, 5), strides=(2, 2), padding='same', use_bias=False))
        model.add(layers.BatchNormalization())
        model.add(layers.LeakyReLU(0.2))

        # Bloque 3: 16x16 -> 32x32
        model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
        model.add(layers.BatchNormalization())
        model.add(layers.LeakyReLU(0.2))

        # Bloque 4: 32x32 -> 64x64
        model.add(layers.Conv2DTranspose(3, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh'))

        return model

    def build_discriminator(self):

        # Discriminador: Clasifica imágenes como reales o falsas.

        model = tf.keras.Sequential(name='Discriminator')

        # Bloque 1: 64x64 -> 32x32
        model.add(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same', input_shape=self.img_shape))
        model.add(layers.LeakyReLU(0.2))
        model.add(layers.Dropout(0.3))

        # Bloque 2: 32x32 -> 16x16
        model.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
        model.add(layers.LeakyReLU(0.2))
        model.add(layers.Dropout(0.3))

        # Bloque 3: 16x16 -> 8x8
        model.add(layers.Conv2D(256, (5, 5), strides=(2, 2), padding='same'))
        model.add(layers.LeakyReLU(0.2))
        model.add(layers.Dropout(0.3))

        # Bloque 4: 8x8 -> 4x4
        model.add(layers.Conv2D(512, (5, 5), strides=(2, 2), padding='same'))
        model.add(layers.LeakyReLU(0.2))
        model.add(layers.Dropout(0.3))

        # Clasificación
        model.add(layers.Flatten())
        model.add(layers.Dense(1))

        return model

    def discriminator_loss(self, real_output, fake_output):
        # Pérdida del discriminador.
        real_loss = self.cross_entropy(tf.ones_like(real_output), real_output)
        fake_loss = self.cross_entropy(tf.zeros_like(fake_output), fake_output)
        return real_loss + fake_loss

    def generator_loss(self, fake_output):
        # Pérdida del generador.
        return self.cross_entropy(tf.ones_like(fake_output), fake_output)

    @tf.function
    def train_step(self, real_images):
        # Un paso de entrenamiento.
        batch_size = tf.shape(real_images)[0]
        noise = tf.random.normal([batch_size, self.latent_dim])

        with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
            # Generar imágenes falsas
            generated_images = self.generator(noise, training=True)

            # Obtener predicciones del discriminador
            real_output = self.discriminator(real_images, training=True)
            fake_output = self.discriminator(generated_images, training=True)

            # Calcular pérdidas
            gen_loss = self.generator_loss(fake_output)
            disc_loss = self.discriminator_loss(real_output, fake_output)

        # Calcular gradientes
        gen_gradients = gen_tape.gradient(gen_loss, self.generator.trainable_variables)
        disc_gradients = disc_tape.gradient(disc_loss, self.discriminator.trainable_variables)

        # Aplicar gradientes
        self.gen_optimizer.apply_gradients(zip(gen_gradients, self.generator.trainable_variables))
        self.disc_optimizer.apply_gradients(zip(disc_gradients, self.discriminator.trainable_variables))

        return gen_loss, disc_loss

    def generate_images(self, num_images=16, seed=None):
        # Genera imágenes usando el generador.
        if seed is not None:
            tf.random.set_seed(seed)
        noise = tf.random.normal([num_images, self.latent_dim])
        generated = self.generator(noise, training=False)
        return generated.numpy()

# Crear instancia de la GAN
gan = DCGAN(latent_dim=LATENT_DIM, img_shape=(IMG_SIZE, IMG_SIZE, 3))

# Callbacks y Utilidades de Entrenamiento

import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import json

class GANCallback:
    # Callback para monitorear el entrenamiento de la GAN.

    def __init__(self, gan, save_path, save_interval=10):
        self.gan = gan
        self.save_path = save_path
        self.save_interval = save_interval

        # Historial de métricas
        self.history = {
            'gen_loss': [],
            'disc_loss': [],
            'epochs': []
        }

        # Seed fijo para visualización consistente
        self.fixed_seed = tf.random.normal([16, gan.latent_dim])

    def on_epoch_end(self, epoch, gen_loss, disc_loss):
        # Se ejecuta al final de cada época.
        # Guardar métricas
        self.history['epochs'].append(epoch)
        self.history['gen_loss'].append(float(gen_loss))
        self.history['disc_loss'].append(float(disc_loss))

        # Guardar imágenes cada N épocas
        if (epoch + 1) % self.save_interval == 0:
            self.save_generated_images(epoch)
            self.save_metrics_plot(epoch)

    def save_generated_images(self, epoch):
        # Guarda una grilla de imágenes generadas.
        # Generar imágenes con seed fijo
        generated = self.gan.generator(self.fixed_seed, training=False)
        generated = (generated + 1) / 2

        fig, axes = plt.subplots(4, 4, figsize=(10, 10))

        for i, ax in enumerate(axes.flatten()):
            ax.imshow(generated[i])
            ax.axis('off')

        plt.suptitle(f'Imágenes Generadas - Época {epoch + 1}', fontsize=14)
        plt.tight_layout()

        save_path = os.path.join(self.save_path, f'generated_epoch_{epoch + 1:04d}.png')
        plt.savefig(save_path, dpi=150)
        plt.close()

    def save_metrics_plot(self, epoch):
        # Guarda gráfico de métricas de entrenamiento.
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Pérdida del Generador
        axes[0].plot(self.history['epochs'], self.history['gen_loss'],
                     'b-', label='Generator Loss', linewidth=2)
        axes[0].set_xlabel('Época')
        axes[0].set_ylabel('Pérdida')
        axes[0].set_title('Pérdida del Generador')
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        # Pérdida del Discriminador
        axes[1].plot(self.history['epochs'], self.history['disc_loss'],
                     'r-', label='Discriminator Loss', linewidth=2)
        axes[1].set_xlabel('Época')
        axes[1].set_ylabel('Pérdida')
        axes[1].set_title('Pérdida del Discriminador')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        plt.suptitle(f'Métricas de Entrenamiento - Época {epoch + 1}', fontsize=14)
        plt.tight_layout()

        save_path = os.path.join(self.save_path, 'training_metrics.png')
        plt.savefig(save_path, dpi=150)
        plt.close()

    def save_history(self):
        # Guarda el historial de entrenamiento en JSON.
        history_path = os.path.join(self.save_path, 'training_history.json')
        with open(history_path, 'w') as f:
            json.dump(self.history, f, indent=2)
        print(f" Historial guardado en: {history_path}")

print("Callbacks definidos correctamente")

# Entrenamiento de la GAN

import time
from tqdm import tqdm

def train_gan(gan, dataset, epochs, callback):

    # Entrena la GAN por 200 épocas.

    start_time = time.time()

    for epoch in range(epochs):
        epoch_start = time.time()

        gen_losses = []
        disc_losses = []

        # Barra de progreso para cada época
        progress_bar = tqdm(dataset, desc=f"Época {epoch + 1}/{epochs}", leave=False)

        for batch in progress_bar:
            gen_loss, disc_loss = gan.train_step(batch)
            gen_losses.append(gen_loss.numpy())
            disc_losses.append(disc_loss.numpy())

            # Actualizar barra de progreso
            progress_bar.set_postfix({
                'G_loss': f'{gen_loss:.4f}',
                'D_loss': f'{disc_loss:.4f}'
            })

        # Promedios de la época
        avg_gen_loss = np.mean(gen_losses)
        avg_disc_loss = np.mean(disc_losses)
        epoch_time = time.time() - epoch_start

        # Callback
        callback.on_epoch_end(epoch, avg_gen_loss, avg_disc_loss)

        # Imprimir resumen de la época
        print(f"Época {epoch + 1:3d}/{epochs} | "
              f"G_loss: {avg_gen_loss:.4f} | "
              f"D_loss: {avg_disc_loss:.4f} | "
              f"Tiempo: {epoch_time:.1f}s")

        # Guardar cada 50 épocas
        if (epoch + 1) % 50 == 0:
            checkpoint_path = os.path.join(MODELS_PATH, f'checkpoint_epoch_{epoch + 1}')
            gan.generator.save(checkpoint_path + '_generator.keras')
            gan.discriminator.save(checkpoint_path + '_discriminator.keras')
            print(f"    Checkpoint guardado en época {epoch + 1}")

    total_time = time.time() - start_time
    print(f"\n ENTRENAMIENTO COMPLETADO")
    print(f" Tiempo total: {total_time/60:.1f} minutos")

    # Guardar historial
    callback.save_history()

    return callback.history

# Configuración del entrenamiento
EPOCHS = 200

# Crear callback
callback = GANCallback(
    gan=gan,
    save_path=IMAGES_PATH,
    save_interval=10  # Guardar cada 10 épocas
)

# Entrenar
history = train_gan(gan, train_dataset, EPOCHS, callback)

# Guardar Modelos Finales

import json
from datetime import datetime

# Guardar generador
generator_path = os.path.join(MODELS_PATH, 'generator_final.keras')
gan.generator.save(generator_path)
print(f"    Generador guardado: {generator_path}")

# Guardar discriminador
discriminator_path = os.path.join(MODELS_PATH, 'discriminator_final.keras')
gan.discriminator.save(discriminator_path)
print(f"   Discriminador guardado: {discriminator_path}")

# Guardar configuración del modelo
config = {
    'latent_dim': LATENT_DIM,
    'img_size': IMG_SIZE,
    'img_shape': (IMG_SIZE, IMG_SIZE, 3),
    'epochs_trained': EPOCHS,
    'dataset': 'brain-tumor-dataset',
    'total_images': len(all_images),
    'batch_size': BATCH_SIZE,
    'date_trained': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    'final_gen_loss': history['gen_loss'][-1],
    'final_disc_loss': history['disc_loss'][-1]
}

config_path = os.path.join(MODELS_PATH, 'model_config.json')
with open(config_path, 'w') as f:
    json.dump(config, f, indent=2)
print(f"   Configuración guardada: {config_path}")

"""## **Cargar GAN ya entrenado**"""

# Montar Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os
import json
import numpy as np
import tensorflow as tf
from PIL import Image
import matplotlib.pyplot as plt
from datetime import datetime
import base64
from io import BytesIO

# Rutas del proyecto
PROJECT_PATH = '/content/drive/MyDrive/Practica_3_IA'
MODELS_PATH = os.path.join(PROJECT_PATH, 'modelos')
IMAGES_PATH = os.path.join(PROJECT_PATH, 'imagenes_generadas')
REPORTS_PATH = os.path.join(PROJECT_PATH, 'reportes')

os.makedirs(REPORTS_PATH, exist_ok=True)

# Cargar configuración del GAN
gan_config_path = os.path.join(MODELS_PATH, 'model_config.json')
with open(gan_config_path, 'r') as f:
    GAN_CONFIG = json.load(f)

# Cargar generador entrenado del GAN
print(" Cargando generador del GAN entrenado...")
GAN_GENERATOR = tf.keras.models.load_model(
    os.path.join(MODELS_PATH, 'generator_final.keras')
)

LATENT_DIM = GAN_CONFIG['latent_dim']

print(" Generador cargado correctamente")
print(f"   └── Dimensión latente: {LATENT_DIM}")
print(f"   └── Épocas entrenadas: {GAN_CONFIG['epochs_trained']}")

"""## **LMM**

*Configuración de APIs (Gemini + Groq)*

### **Configuración de APIs**

1.   Elemento de la lista
2.   Elemento de la lista
"""

import os
from google.colab import userdata

# Verificar instalación de LangChain
print("🔍 Verificando instalación de LangChain...")
try:
    import langchain
    from langchain_core.tools import tool
    print(f"  langchain: {langchain.__version__}")
except ImportError as e:
    print(f"   Error: {e}")

print("\n" + "=" * 60)
print(" CONFIGURACIÓN DE APIs")
print("=" * 60)

# Google Gemini API
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
GOOGLE_API_ENV = "GOOGLE_API_KEY"
os.environ[GOOGLE_API_ENV] = GOOGLE_API_KEY

# Groq API
GROQ_API_KEY = userdata.get('GROQ_API_KEY')
GROQ_API_ENV = "GROQ_API_KEY"
os.environ[GROQ_API_ENV] = GROQ_API_KEY

print("\n APIs configuradas correctamente")

"""### **Inicializar LLMs (Gemini + Groq)**"""

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq

# Gemini (multimodal)
LLM_GEMINI = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=GOOGLE_API_KEY,
    temperature=0.3
)

# Groq (razonamiento médico)
LLM_GROQ = ChatGroq(
    model="llama-3.1-8b-instant",
    groq_api_key=GROQ_API_KEY,
    temperature=0.3
)

print("🔍 Verificando conexión con LLMs...")

try:
    response = LLM_GEMINI.invoke("Responde solo 'OK'")
    print(f"   Gemini: {response.content.strip()}")
except Exception as e:
    print(f"    Gemini error: {e}")

try:
    response = LLM_GROQ.invoke("Responde solo 'OK'")
    print(f"    Groq: {response.content.strip()}")
except Exception as e:
    print(f"    Groq error: {e}")

print("\n LLMs inicializados correctamente")

"""### **Funciones Auxiliares**"""

import base64
from io import BytesIO
from PIL import Image
import numpy as np

def image_to_base64(image_array):
    if image_array.max() <= 1.0:
        image_array = (image_array * 255).astype(np.uint8)

    pil_image = Image.fromarray(image_array)
    buffer = BytesIO()
    pil_image.save(buffer, format='PNG')
    buffer.seek(0)

    return base64.b64encode(buffer.read()).decode('utf-8')

def base64_to_image(base64_string):
    image_data = base64.b64decode(base64_string)
    image = Image.open(BytesIO(image_data))
    return np.array(image)

def save_image(image_array, filename):
    if image_array.max() <= 1.0:
        image_array = (image_array * 255).astype(np.uint8)
    save_path = os.path.join(REPORTS_PATH, filename)
    Image.fromarray(image_array).save(save_path)
    return save_path

def display_image(image_array, title="Imagen"):
    plt.figure(figsize=(4, 4))
    plt.imshow(image_array)
    plt.title(title)
    plt.axis('off')
    plt.show()

# === Estado global del sistema ===
STATE_LAST_IMAGE = None
STATE_LAST_ANALYSIS = None
STATE_SESSION_HISTORY = []

print(" Funciones auxiliares definidas")

"""### **Tools**"""

from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import json

# TOOL 1: Generar Imagen con GAN
@tool
def generar_imagen_gan(seed: int = None) -> str:
    """
    Genera una imagen sintética de MRI cerebral usando la GAN entrenada.
    """
    global STATE_LAST_IMAGE, STATE_SESSION_HISTORY

    if seed is not None:
        tf.random.set_seed(seed)
    else:
        seed = np.random.randint(0, 10000)
        tf.random.set_seed(seed)

    noise = tf.random.normal([1, LATENT_DIM])

    generated = GAN_GENERATOR(noise, training=False)
    image_array = (generated[0].numpy() + 1) / 2
    image_array = np.clip(image_array, 0, 1)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"mri_generated_{timestamp}_seed{seed}.png"
    save_path = save_image(image_array, filename)

    STATE_LAST_IMAGE = {
        'array': image_array,
        'path': save_path,
        'seed': seed,
        'timestamp': timestamp,
        'base64': image_to_base64(image_array)
    }

    STATE_SESSION_HISTORY.append({
        'accion': 'generar_imagen_gan',
        'timestamp': timestamp,
        'seed': seed,
        'path': save_path
    })

    display_image(image_array, f"MRI Generada (seed={seed})")

    return (
        " Imagen de MRI cerebral generada exitosamente.\n"
        f"   - Seed utilizada: {seed}\n"
        f"   - Guardada en: {save_path}"
    )


# TOOL 2: Analizar Imagen con LLM
@tool
def analizar_imagen_llm(descripcion_adicional: str = "") -> str:
    """
    Analiza la última imagen de MRI generada usando Gemini (visión).
    """
    global STATE_LAST_IMAGE, STATE_LAST_ANALYSIS, STATE_SESSION_HISTORY

    if STATE_LAST_IMAGE is None:
        return " No hay imagen para analizar. Primero genera una imagen."

    prompt = """Eres un radiólogo experto analizando una imagen de resonancia magnética (MRI) cerebral.
Proporciona una descripción general, hallazgos relevantes y una impresión inicial.
Imagen generada por IA con fines educativos.
"""

    if descripcion_adicional:
        prompt += f"\nContexto adicional del paciente: {descripcion_adicional}"

    message = HumanMessage(
        content=[
            {"type": "text", "text": prompt},
            {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/png;base64,{STATE_LAST_IMAGE['base64']}"
                }
            }
        ]
    )

    response = LLM_GEMINI.invoke([message])
    analysis = response.content

    STATE_LAST_ANALYSIS = {
        'analisis': analysis,
        'imagen_path': STATE_LAST_IMAGE['path'],
        'timestamp': datetime.now().strftime("%Y%m%d_%H%M%S"),
        'contexto': descripcion_adicional
    }

    STATE_SESSION_HISTORY.append({
        'accion': 'analizar_imagen_llm',
        'timestamp': STATE_LAST_ANALYSIS['timestamp'],
        'imagen_analizada': STATE_LAST_IMAGE['path'],
        'resumen': analysis[:200] + "..."
    })

    return f" **ANÁLISIS DE IMAGEN MRI**\n\n{analysis}"


# TOOL 3: Diagnóstico con LLM
@tool
def diagnostico_tumor_llm(sintomas_paciente: str = "") -> str:
    """
    Evaluación diagnóstica basada en el análisis previo.
    """
    global STATE_LAST_ANALYSIS, STATE_SESSION_HISTORY

    if STATE_LAST_ANALYSIS is None:
        return " No hay análisis previo."

    prompt = f"""Eres un neurólogo especialista en neuro-oncología.

ANÁLISIS RADIOLÓGICO:
{STATE_LAST_ANALYSIS['analisis']}

SÍNTOMAS:
{sintomas_paciente or "No especificados"}
"""

    response = LLM_GROQ.invoke(prompt)
    diagnostico = response.content

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    STATE_SESSION_HISTORY.append({
        'accion': 'diagnostico_tumor_llm',
        'timestamp': timestamp,
        'sintomas': sintomas_paciente,
        'resumen': diagnostico[:200] + "..."
    })

    return f" **EVALUACIÓN DIAGNÓSTICA**\n\n{diagnostico}"


# TOOL 4: Comparar Imágenes
@tool
def comparar_imagenes(num_imagenes: int = 4) -> str:
    """
    Genera múltiples imágenes para observar variabilidad de la GAN.
    """
    global STATE_SESSION_HISTORY

    num_imagenes = max(2, min(9, num_imagenes))
    images, seeds = [], []

    for _ in range(num_imagenes):
        seed = np.random.randint(0, 10000)
        seeds.append(seed)
        tf.random.set_seed(seed)
        noise = tf.random.normal([1, LATENT_DIM])
        generated = GAN_GENERATOR(noise, training=False)
        images.append((generated[0].numpy() + 1) / 2)

    cols = min(3, num_imagenes)
    rows = (num_imagenes + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(4*cols, 4*rows))
    axes = axes.flatten()

    for i, ax in enumerate(axes):
        if i < len(images):
            ax.imshow(images[i])
            ax.set_title(f'MRI {i+1} (seed={seeds[i]})')
        ax.axis('off')

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = os.path.join(REPORTS_PATH, f'comparacion_{timestamp}.png')
    plt.savefig(save_path, dpi=150)
    plt.show()

    STATE_SESSION_HISTORY.append({
        'accion': 'comparar_imagenes',
        'timestamp': timestamp,
        'seeds': seeds,
        'path': save_path
    })

    return f"Comparación de imágenes generada y guardada en {save_path}"


# TOOL 5: Generar Reporte Médico
@tool
def generar_reporte_medico(nombre_paciente="Paciente Anónimo", edad=0, motivo_consulta="") -> str:
    """
    Genera un reporte médico estructurado.
    """
    global STATE_LAST_ANALYSIS, STATE_SESSION_HISTORY

    if STATE_LAST_ANALYSIS is None:
        return "No hay análisis disponible."

    prompt = f"""Genera un reporte médico profesional basado en este análisis:
{STATE_LAST_ANALYSIS['analisis']}
"""

    response = LLM_GROQ.invoke(prompt)
    reporte = response.content

    filename = f"reporte_medico_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    path = os.path.join(REPORTS_PATH, filename)

    with open(path, "w", encoding="utf-8") as f:
        f.write(reporte)

    STATE_SESSION_HISTORY.append({
        'accion': 'generar_reporte_medico',
        'paciente': nombre_paciente,
        'path': path
    })

    return f"Reporte médico generado y guardado en {path}"


# Registro de tools
tools = [
    generar_imagen_gan,
    analizar_imagen_llm,
    diagnostico_tumor_llm,
    comparar_imagenes,
    generar_reporte_medico
]

print("5 Tools definidas correctamente")

"""## **Agente IA**

### **Instalación de Dependencias**
"""

print("\nPaso 1: Instalando paquetes compatibles...")

# Instalar todo junto para que pip resuelva las dependencias correctamente
!pip install --quiet \
    langchain==0.2.16 \
    langchain-core==0.2.40 \
    langchain-google-genai==1.0.10 \
    langchain-groq==0.1.10 \
    google-generativeai==0.7.2 \
    pillow

print("\nInstalación completada")

# Verificar
print("\nVersiones instaladas:")
!pip show langchain langchain-core langchain-google-genai langchain-groq google-generativeai 2>/dev/null | grep -E "^(Name|Version):"

"""### **Crear el Agente con LangChain**"""

from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

SYSTEM_PROMPT = """Eres un asistente médico especializado en análisis de imágenes de resonancia magnética (MRI) cerebral para detección de tumores.

Tu rol es ayudar a profesionales de la salud a:
1. Generar imágenes sintéticas de MRI cerebral para entrenamiento y estudio
2. Analizar imágenes de MRI identificando posibles anomalías
3. Proporcionar evaluaciones diagnósticas preliminares
4. Generar reportes médicos estructurados

HERRAMIENTAS DISPONIBLES:
1. **generar_imagen_gan**
2. **analizar_imagen_llm**
3. **diagnostico_tumor_llm**
4. **comparar_imagenes**
5. **generar_reporte_medico**

IMPORTANTE:
- Las imágenes son sintéticas y educativas
- No reemplaza diagnóstico médico real
- Responde siempre en español
"""

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

# USAR VARIABLE EXISTENTE
agent = create_tool_calling_agent(
    llm=LLM_GROQ,
    tools=tools,
    prompt=prompt
)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True,
    max_iterations=10
)

print("Agente creado correctamente")

"""###**Crear el Logger**

"""

import time
import json

class AgentLogger:

    def __init__(self):
        self.logs = []

    def log_interaction(self, user_input, agent_response, tools_used, reasoning, tool_outputs):
        entry = {
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "user_input": user_input,
            "agent_response": agent_response,
            "tools_used": tools_used,
            "reasoning_steps": reasoning,
            "tool_outputs": tool_outputs
        }
        self.logs.append(entry)

    def show_summary(self):
        print("\n" + "=" * 60)
        print("RESUMEN DE TRAZABILIDAD DEL AGENTE")
        print("=" * 60)

        if not self.logs:
            print("⚠ No hay interacciones registradas.")
            return

        for i, entry in enumerate(self.logs, 1):
            print(f"\n🔹 Interacción #{i}")
            print(f"{entry['timestamp']}")
            print(f"Usuario: {entry['user_input']}")
            print(f"Respuesta del agente: {entry['agent_response']}")

            print("\nRazonamiento:")
            for r in entry["reasoning_steps"]:
                print(f"   - {r}")

            print("\n🛠 Herramientas usadas:")
            for t in entry["tools_used"]:
                print(f"   - {t}")

            print("\nResultados de herramientas:")
            for o in entry["tool_outputs"]:
                print(f"   - {str(o)[:120]}...")

    def save_to_json(self, filename="agent_trace.json"):
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(self.logs, f, indent=4, ensure_ascii=False)
        print(f"\nArchivo de trazabilidad guardado en: {filename}")


# Definir el logger aquí
logger = AgentLogger()

"""### **Interfaz de Chat con el Agente**"""

def chat_with_agent(user_input: str, show_trace: bool = True):
    print("\n" + "=" * 60)
    print(f"Usuario: {user_input}")
    print("=" * 60)

    try:
        response = agent_executor.invoke({
            "input": user_input,
            "chat_history": []
        })

        agent_response = response['output']

        intermediate_steps = response.get("intermediate_steps", [])

        reasoning_logs = []
        tool_calls = []
        tool_results = []

        for step in intermediate_steps:
          action, result = step
          reasoning_logs.append(action.log)
          tool_calls.append(action.tool)
          tool_results.append(result)

        # Guardar trazabilidad completa
        logger.log_interaction(
            user_input=user_input,
            agent_response=agent_response,
            tools_used=tool_calls,
            reasoning=reasoning_logs,
            tool_outputs=tool_results
        )

        print("\n" + "-" * 60)
        print(f"Agente:\n{agent_response}")
        print("-" * 60)

        return agent_response

    except Exception as e:
        error_msg = f"Error: {str(e)}"
        print(f"\n {error_msg}")
        return error_msg


def interactive_session():
    print("\n" + "=" * 60)
    print("SISTEMA DE ANÁLISIS DE MRI CEREBRAL")
    print("=" * 60)

    while True:
        try:
            user_input = input("\nTú: ").strip()

            if not user_input:
                continue

            if user_input.lower() in ['salir', 'exit', 'quit']:
                logger.show_summary()
                print("\n¡Hasta luego!")
                break

            if user_input.lower() == 'historial':
                print("\nHistorial de herramientas:")
                for i, h in enumerate(STATE_SESSION_HISTORY, 1):
                    print(f"   {i}. [{h['timestamp']}] {h['accion']}")
                continue

            if user_input.lower() == 'resumen':
                logger.show_summary()
                continue

            if user_input.lower() == 'ayuda':
                print("Usa lenguaje natural para interactuar con el agente.")
                continue

            chat_with_agent(user_input)

        except KeyboardInterrupt:
            logger.show_summary()
            print("\n\n Sesión interrumpida.")
            break


print("Interfaz de chat lista")

"""## **Prueba**"""

print("=" * 60)
print("DEMOSTRACIÓN DEL SISTEMA AGENTIC AI")
print("=" * 60)

# Demo 1: Generar imagen
print("\nPASO 1: Generar imagen de MRI")
print("-" * 40)
response1 = chat_with_agent("Genera una imagen de resonancia magnética cerebral")

# Demo 2: Analizar imagen
print("\nPASO 2: Analizar la imagen")
print("-" * 40)
response2 = chat_with_agent("Analiza la imagen de MRI que acabas de generar")

# Demo 3: Diagnóstico
print("\nPASO 3: Obtener diagnóstico")
print("-" * 40)
response3 = chat_with_agent(
    "Dame un diagnóstico considerando que el paciente es un hombre de 52 años "
    "que presenta dolores de cabeza intensos desde hace 3 meses y episodios de visión borrosa"
)

# la siguiente línea sirve para iniciar un chat interactivo
# interactive_session()
# O usa consultas individuales
# chat_with_agent("tu consulta aquí")